---
name: bash-language-server
description: A language server for Bash.
homepage: https://github.com/bash-lsp/bash-language-server
licenses:
  - MIT
languages:
  - Bash
categories:
  - LSP

source:
  id: pkg:npm/bash-language-server@3.0.0

bin:
  bash-language-server: npm:bash-language-server
